/* East Coast AC & Heating Ltd â€” SEO silo content. Generated by scripts/_eastcoast_build.js */
const SITE = {
  "name": "East Coast AC & Heating Ltd",
  "legalName": "East Coast AC & Heating Ltd",
  "phone": "778-344-4938",
  "phoneIntl": "+1-778-344-4938",
  "phoneDigits": "17783444938",
  "email": "",
  "ctaLabel": "Call 778-344-4938",
  "ctaHref": "tel:+17783444938",
  "handle": "eastcoastacbc",
  "domain": "https://eastcoastheating.ca",
  "address": {
    "street": "7156 144 St, Unit 18",
    "city": "Surrey",
    "region": "BC",
    "postal": "",
    "country": "CA"
  },
  "rating": "",
  "reviewCount": "",
  "reviewsUrl": "/contact.html",
  "whatsapp": "/contact.html",
  "geo": null,
  "sameAs": [],
  "founded": "",
  "yearsExperience": "",
  "jobsCompleted": "",
  "licenseNumber": "",
  "logo": "/images/eastcoast-logo.svg"
};
const COMBO_SERVICE_SLUGS = [
  "emergency-hvac",
  "furnace-repair",
  "ac-repair",
  "heat-pumps",
  "boilers",
  "ductless-mini-split",
  "hvac-maintenance",
  "thermostats",
  "frozen-pipes",
  "furnace-safety",
  "commercial-hvac",
  "strata-hvac"
];
const SERVICES = [
  {
    "slug": "emergency-hvac",
    "category": "residential",
    "nav": "24/7 Emergency HVAC",
    "h1": "24/7 Emergency Heating & Cooling in Surrey & the Lower Mainland",
    "metaTitle": "24/7 Emergency HVAC Surrey & Lower Mainland | No Heat, No AC | East Coast AC & Heating",
    "metaDesc": "No heat, no cooling, frozen pipes, or a furnace that will not start? East Coast AC & Heating dispatches 24/7 emergency HVAC service across Surrey and the Lower Mainland. Request a quote â€” 778-344-4938.",
    "image": "van.jpg",
    "heroSub": "When the furnace dies on a cold night or the AC fails in a heat wave, you need a real HVAC crew â€” not an answering service. Request service through our contact form and we will get back to you as fast as we can.",
    "intro": [
      "Heating and cooling emergencies do not keep business hours. East Coast AC & Heating Ltd runs a 24/7 emergency HVAC service for Surrey, Vancouver, Burnaby, Langley and the rest of the Lower Mainland. No heat, no cooling, a furnace that will not ignite, strange smells from the furnace, or frozen pipes tied to a failed heating system â€” those are the calls we take first.",
      "Before any work starts you get a clear plan and an upfront quote. We diagnose the root cause, make the system safe, and restore heat or cooling. We do not invent prices on this site â€” every job is quoted for your equipment and home."
    ],
    "bulletsTitle": "Emergencies we handle",
    "bullets": [
      "No heat / furnace will not start",
      "No cooling / AC down in summer",
      "Strange smells from the furnace",
      "Carbon monoxide alarm or suspected furnace exhaust issues",
      "Frozen pipes related to heating failure",
      "Heat pump not heating or cooling",
      "Boiler not producing heat",
      "Thermostat dead or system short-cycling"
    ],
    "stepsTitle": "What happens when you request emergency service",
    "steps": [
      [
        "Tell us what failed",
        "Use the contact form â€” 778-344-4938. Describe no heat, no cooling, smells, or frozen pipes so we can triage fast."
      ],
      [
        "We confirm and dispatch",
        "A licensed HVAC technician reviews the call and we schedule the fastest safe response we can offer."
      ],
      [
        "Upfront quote on site",
        "You approve a clear price before we begin. No mystery invoices after the repair."
      ],
      [
        "Made safe and running",
        "We restore heat or cooling and explain what failed so it is less likely to happen again."
      ]
    ],
    "faqs": [
      [
        "Do you offer true 24/7 emergency HVAC service?",
        "Yes. We frame emergency heating and cooling the same way a 24/7 trade should: nights, weekends and holidays. Request service through the form until our public number is live."
      ],
      [
        "What should I do if I smell something strange from the furnace?",
        "If you suspect carbon monoxide or you feel unwell, leave the home and call 911. If it is a burning-dust smell at first start-up in fall, that can be normal â€” still request service if it persists or you are unsure."
      ],
      [
        "Can you help if pipes are frozen?",
        "Yes, when frozen pipes are tied to a heating failure. We restore heat and help you protect the plumbing. If a pipe has already burst, shut the water if it is safe and request emergency service."
      ]
    ],
    "related": [
      "furnace-repair",
      "furnace-safety",
      "frozen-pipes"
    ]
  },
  {
    "slug": "furnace-repair",
    "category": "residential",
    "nav": "Furnace Repair & Install",
    "h1": "Furnace Repair & Installation",
    "metaTitle": "Furnace Repair & Installation Surrey & Lower Mainland | East Coast AC & Heating",
    "metaDesc": "Furnace will not start, short-cycles, or needs replacement? East Coast AC & Heating repairs and installs furnaces across Surrey and the Lower Mainland. Request a quote â€” 778-344-4938.",
    "image": "van.jpg",
    "heroSub": "From a furnace that will not ignite to a full replacement, we service gas furnaces in Surrey homes and across the Lower Mainland â€” quoted before we start.",
    "intro": [
      "A furnace that will not start, keeps cycling, or no longer keeps up is one of the most common winter calls in Surrey. East Coast AC & Heating Ltd diagnoses ignition, flame-sensing, airflow, and control issues and repairs them when the equipment is worth saving.",
      "When a furnace is at the end of its life, we install a properly sized replacement, pull required permits, and walk you through the new system. We do not publish made-up prices â€” you get a written quote for your home."
    ],
    "bulletsTitle": "Furnace work we do",
    "bullets": [
      "No-heat diagnosis and repair",
      "Igniter, flame sensor, and control repairs",
      "Blower motor and limit-switch service",
      "Gas furnace replacement and install",
      "High-efficiency furnace upgrades",
      "Filter, airflow, and venting checks",
      "Permits where the municipality requires them",
      "Post-install walkthrough and settings"
    ],
    "stepsTitle": "How a furnace job runs",
    "steps": [
      [
        "Diagnosis",
        "We confirm whether the problem is the furnace, thermostat, venting, or airflow."
      ],
      [
        "Quote",
        "You get a clear repair-or-replace recommendation and a written price."
      ],
      [
        "Repair or install",
        "We complete the work with the parts and equipment quoted â€” no bait-and-switch."
      ],
      [
        "Test & handover",
        "We verify heat, safety devices, and explain filters and maintenance."
      ]
    ],
    "faqs": [
      [
        "Should I repair or replace my furnace?",
        "If the heat exchanger is cracked, parts are obsolete, or repair cost is close to a new unit, replacement is usually the honest answer. We will say so plainly."
      ],
      [
        "Do you install high-efficiency furnaces?",
        "Yes. We size the equipment to the home rather than swapping like-for-like blindly."
      ],
      [
        "How do I request service?",
        "Call 778-344-4938 or use the contact form. â€” Or use the contact form."
      ]
    ],
    "related": [
      "hvac-maintenance",
      "heat-pumps",
      "emergency-hvac"
    ]
  },
  {
    "slug": "ac-repair",
    "category": "residential",
    "nav": "AC Repair & Install",
    "h1": "Air Conditioning Repair & Installation",
    "metaTitle": "AC Repair & Installation Surrey & Lower Mainland | East Coast AC & Heating",
    "metaDesc": "AC down in summer? East Coast AC & Heating repairs and installs central air conditioning across Surrey and the Lower Mainland. Request a quote â€” 778-344-4938.",
    "image": "exhaust-fan-installation-surrey.jpg",
    "heroSub": "When the AC dies in a Lower Mainland heat wave, we diagnose, repair, or install cooling so the house is livable again.",
    "intro": [
      "South Surrey, Vancouver, and much of the Lower Mainland now see summer temperatures that older homes were never designed for. East Coast AC & Heating Ltd repairs central air conditioners and installs new cooling when the old system cannot keep up.",
      "We check refrigerant circuit health, outdoor fans, coils, and indoor airflow. New installs are sized to the home. Quotes are written â€” we do not list invented cooling prices on the website."
    ],
    "bulletsTitle": "Cooling services",
    "bullets": [
      "No-cooling diagnosis",
      "Central AC repair",
      "Capacitor, contactor, and fan motor service",
      "New central air installation",
      "Coil cleaning and airflow correction",
      "Matching indoor and outdoor equipment",
      "Permits where required",
      "Seasonal start-up checks"
    ],
    "stepsTitle": "From no-cool to comfort",
    "steps": [
      [
        "Find the failure",
        "We test the outdoor unit, indoor coil, and controls before recommending parts."
      ],
      [
        "Quote the fix",
        "Repair when it is honest; replace when the system is spent."
      ],
      [
        "Complete the work",
        "Repairs and installs are done with listed equipment and a clear scope."
      ],
      [
        "Verify cooling",
        "We confirm supply temperatures and explain how to run the system efficiently."
      ]
    ],
    "faqs": [
      [
        "Can you add AC to a furnace system?",
        "Often yes, if the furnace and ductwork can support a matching coil. We assess that before quoting a new condenser."
      ],
      [
        "Heat pump vs air conditioner?",
        "A heat pump cools in summer and heats in shoulder seasons. We will explain which fits your home without pushing a product you do not need."
      ],
      [
        "Do you service all brands?",
        "We service common residential brands. If a part is obsolete we will tell you before you spend money chasing it."
      ]
    ],
    "related": [
      "heat-pumps",
      "ductless-mini-split",
      "emergency-hvac"
    ]
  },
  {
    "slug": "heat-pumps",
    "category": "residential",
    "nav": "Heat Pumps",
    "h1": "Heat Pump Installation & Service",
    "metaTitle": "Heat Pump Installation & Service Surrey & Lower Mainland | East Coast AC & Heating",
    "metaDesc": "Heat pump installation, repair and service in Surrey and the Lower Mainland. East Coast AC & Heating sizes and installs ducted and ductless systems. Request a quote.",
    "image": "fleetwood-panel-heat-pump-ev.jpg",
    "heroSub": "A properly sized heat pump heats and cools efficiently through most Lower Mainland weather. We install and service ducted and ductless systems.",
    "intro": [
      "Heat pumps are one of the most practical comfort upgrades in coastal BC: heating for most of the winter and cooling for summer, from one system. East Coast AC & Heating Ltd designs installs around your home â€” not a one-size outdoor unit dropped on a pad.",
      "We also service existing heat pumps that have lost capacity, ice up, or will not switch modes. Rebate programs change; we do not invent rebate amounts here. We can discuss current programs when you request a quote."
    ],
    "bulletsTitle": "Heat pump work",
    "bullets": [
      "Ducted heat pump installation",
      "Ductless and multi-zone heat pumps",
      "Heat pump repair and diagnostics",
      "Backup heat coordination with a furnace",
      "Line-set, pad, and outdoor placement",
      "Thermostat and control setup",
      "Permit support where required",
      "Seasonal maintenance"
    ],
    "stepsTitle": "How we approach a heat pump project",
    "steps": [
      [
        "Home review",
        "We look at insulation, ductwork, and how you actually use the house."
      ],
      [
        "Equipment selection",
        "We propose a size and type that fits â€” ducted, ductless, or hybrid."
      ],
      [
        "Install",
        "Outdoor unit, indoor equipment, and controls are installed as a matched system."
      ],
      [
        "Commissioning",
        "We verify heating and cooling modes and show you how to run it."
      ]
    ],
    "faqs": [
      [
        "Will a heat pump work in a Surrey winter?",
        "Modern cold-climate heat pumps handle typical Lower Mainland winters. Some homes still want furnace backup for the coldest snaps â€” we will say if yours does."
      ],
      [
        "Do you handle ductless mini-splits too?",
        "Yes. See our ductless mini-split service for homes without usable ductwork."
      ],
      [
        "Can you quote without a site visit?",
        "We can discuss options from photos, but a proper install quote needs to see the home."
      ]
    ],
    "related": [
      "ductless-mini-split",
      "furnace-repair",
      "ac-repair"
    ]
  },
  {
    "slug": "boilers",
    "category": "residential",
    "nav": "Boilers",
    "h1": "Boiler Repair & Installation",
    "metaTitle": "Boiler Repair & Installation Surrey & Lower Mainland | East Coast AC & Heating",
    "metaDesc": "Boiler not heating? East Coast AC & Heating repairs and installs residential boilers and hydronic heat in Surrey and the Lower Mainland. Request a quote.",
    "image": "commercial project.jpg",
    "heroSub": "Hydronic heat is quiet and even when it is running right. We repair and replace boilers for homes that rely on hot water heat.",
    "intro": [
      "Many older Lower Mainland homes and some newer custom builds still heat with a boiler and radiators or in-floor loops. When that system fails, rooms go cold even if the rest of the house looks fine. East Coast AC & Heating Ltd diagnoses boiler lockouts, circulation, and zone issues.",
      "Replacement boilers are specified to the existing distribution system. We do not invent package prices online."
    ],
    "bulletsTitle": "Boiler services",
    "bullets": [
      "No-heat boiler diagnosis",
      "Circulator and zone-valve repair",
      "Expansion tank and pressure issues",
      "Boiler replacement and install",
      "Hydronic system checks",
      "Indirect water heater connections where present",
      "Safety and venting review",
      "Seasonal maintenance"
    ],
    "stepsTitle": "Boiler service process",
    "steps": [
      [
        "Inspect the plant",
        "We check the boiler, pumps, zones, and fill/pressure."
      ],
      [
        "Recommend a path",
        "Repair, parts, or replacement â€” explained in plain language."
      ],
      [
        "Complete the work",
        "Repairs or a new boiler with the quoted scope."
      ],
      [
        "Confirm heat at the rooms",
        "We verify zones actually get hot, not just that the boiler fires."
      ]
    ],
    "faqs": [
      [
        "Is my boiler worth repairing?",
        "If the heat exchanger is failed or parts are unobtainable, replacement is the honest call. Otherwise a repair can be the right spend."
      ],
      [
        "Do you work on in-floor heat?",
        "We service the boiler and circulation that feeds in-floor loops. Complex manifold redesigns are quoted separately after we see the system."
      ],
      [
        "How do I book?",
        "Call 778-344-4938 or request a quote through the contact form."
      ]
    ],
    "related": [
      "furnace-repair",
      "hvac-maintenance",
      "emergency-hvac"
    ]
  },
  {
    "slug": "ductless-mini-split",
    "category": "residential",
    "nav": "Ductless Mini-Splits",
    "h1": "Ductless Mini-Split Installation & Service",
    "metaTitle": "Ductless Mini-Split Surrey & Lower Mainland | East Coast AC & Heating",
    "metaDesc": "Ductless mini-split heat pumps for homes without ducts. Install and service in Surrey and the Lower Mainland from East Coast AC & Heating. Request a quote.",
    "image": "exhaust-fan-installation-surrey.jpg",
    "heroSub": "No ducts? A ductless mini-split can heat and cool a suite, addition, or whole small home without ripping out walls for ductwork.",
    "intro": [
      "Suites, laneway homes, heritage houses, and additions often have no usable ductwork. Ductless mini-splits put heating and cooling exactly where you need it. East Coast AC & Heating Ltd installs single-zone and multi-zone systems and services units that no longer cool or heat.",
      "Placement of the outdoor unit, condensate, and line-set route matters as much as the brand. We quote that path honestly."
    ],
    "bulletsTitle": "Mini-split work",
    "bullets": [
      "Single-zone ductless installs",
      "Multi-zone (multi-head) systems",
      "Suite and addition comfort",
      "Repair of existing mini-splits",
      "Line-set and condensate routing",
      "Outdoor unit placement",
      "Controller setup",
      "Maintenance and coil cleaning"
    ],
    "stepsTitle": "A typical mini-split install",
    "steps": [
      [
        "Walk the space",
        "We confirm indoor head locations and a legal, quiet outdoor pad or wall bracket."
      ],
      [
        "Quote the zone plan",
        "One head or several â€” sized to the rooms, not guessed from square footage alone."
      ],
      [
        "Install",
        "Indoor heads, outdoor unit, and lines are installed as a sealed system."
      ],
      [
        "Test both modes",
        "We verify heating and cooling and show you the remote or app controls."
      ]
    ],
    "faqs": [
      [
        "Can one outdoor unit serve several rooms?",
        "Yes â€” multi-zone systems do that. Each extra head is a cost and a design choice; we will not oversell heads you do not need."
      ],
      [
        "Are mini-splits noisy?",
        "Indoor heads are typically quiet when sized and installed correctly. Outdoor placement is what neighbours notice â€” we plan for that."
      ],
      [
        "Do you service brands you did not install?",
        "Often yes, if parts are available. We will tell you if a unit is orphaned."
      ]
    ],
    "related": [
      "heat-pumps",
      "ac-repair",
      "strata-hvac"
    ]
  },
  {
    "slug": "hvac-maintenance",
    "category": "residential",
    "nav": "Maintenance",
    "h1": "Seasonal HVAC Maintenance",
    "metaTitle": "Furnace & AC Maintenance Surrey & Lower Mainland | East Coast AC & Heating",
    "metaDesc": "Seasonal furnace, heat pump and AC maintenance in Surrey and the Lower Mainland. East Coast AC & Heating keeps systems safer and more reliable. Request a quote.",
    "image": "van-guy.jpg",
    "heroSub": "A fall furnace clean-and-check and a spring cooling check catch a lot of no-heat and no-cool calls before they become emergencies.",
    "intro": [
      "Most no-heat calls in October and no-cool calls in June are systems that were never checked. East Coast AC & Heating Ltd offers seasonal maintenance for furnaces, boilers, heat pumps, and air conditioners serving Surrey and the Lower Mainland.",
      "Maintenance is not a made-up certification or a scare pitch. We inspect, clean what should be cleaned, test safety devices, and tell you if something is actually failing."
    ],
    "bulletsTitle": "What a maintenance visit covers",
    "bullets": [
      "Furnace burners, igniter, and flame sensor",
      "Filter and airflow review",
      "Safety switch and limit checks",
      "Heat pump / AC coil and outdoor unit check",
      "Condensate drain where applicable",
      "Thermostat operation",
      "Visible venting and outdoor clearances",
      "A plain-language report of what we found"
    ],
    "stepsTitle": "How maintenance works",
    "steps": [
      [
        "Book a seasonal visit",
        "Fall for heat, spring for cooling â€” or both if you run a heat pump year-round."
      ],
      [
        "We service the equipment",
        "Inspection, cleaning, and tests on the system you actually have."
      ],
      [
        "We tell you the truth",
        "If a part is weak we quote it. If everything is fine we say that too."
      ],
      [
        "You stay ahead of emergencies",
        "Clean equipment fails less often on the first cold or hot weekend."
      ]
    ],
    "faqs": [
      [
        "How often should a furnace be serviced?",
        "Once a year before heating season is the usual recommendation. Heat pumps benefit from a check in both heating and cooling seasons."
      ],
      [
        "Do you sell a membership with fake discounts?",
        "No invented club prices on this site. Ask for a maintenance quote and we will price the visit honestly."
      ],
      [
        "Is maintenance the same as a repair?",
        "No. If we find a failed part, that repair is quoted separately so you can approve it."
      ]
    ],
    "related": [
      "furnace-repair",
      "ac-repair",
      "thermostats"
    ]
  },
  {
    "slug": "thermostats",
    "category": "residential",
    "nav": "Thermostats",
    "h1": "Thermostat Installation & Comfort Controls",
    "metaTitle": "Thermostat Installation Surrey & Lower Mainland | East Coast AC & Heating",
    "metaDesc": "Thermostat replacement and control setup for furnaces, heat pumps and AC in Surrey and the Lower Mainland. East Coast AC & Heating. Request a quote.",
    "image": "smart-home-control-panel-automation.jpg",
    "heroSub": "A dead, confusing, or mismatched thermostat can look like a failed furnace. We install and set up controls that actually match the equipment.",
    "intro": [
      "Wrong thermostat wiring or a heat-pump thermostat left on the wrong mode is a classic 'no heat / no cool' call. East Coast AC & Heating Ltd installs conventional and heat-pump thermostats and sets them up so the system runs the way it was designed.",
      "We do not pretend every Wi-Fi thermostat is a good idea on every boiler or two-stage furnace. Compatibility comes first."
    ],
    "bulletsTitle": "Control work we do",
    "bullets": [
      "Thermostat replacement",
      "Heat-pump thermostat setup",
      "Wi-Fi thermostat installs when compatible",
      "C-wire / power assessment",
      "Mode and schedule walkthrough",
      "Zoning controls (quoted after we see the system)",
      "Fixing mismatched heat/cool changeover",
      "Lockout and dual-fuel settings on hybrids"
    ],
    "stepsTitle": "Getting controls right",
    "steps": [
      [
        "Identify the system",
        "Furnace, boiler, AC, heat pump, or hybrid â€” the thermostat has to match."
      ],
      [
        "Confirm power and wiring",
        "Some digital stats need a common wire; we will not force an incompatible model."
      ],
      [
        "Install and configure",
        "Correct system type, stages, and changeover."
      ],
      [
        "Show you the settings",
        "Heat, cool, auto, and schedules explained without the app-store pitch."
      ]
    ],
    "faqs": [
      [
        "My thermostat is blank â€” is the furnace dead?",
        "Not always. Batteries, a tripped breaker at the furnace, or a failed transformer can look identical. We diagnose both."
      ],
      [
        "Can you install a smart thermostat on a heat pump?",
        "Often, if the model supports heat-pump changeover and auxiliary heat. We will not install one that fights the equipment."
      ],
      [
        "Do you quote thermostats without a visit?",
        "Simple swaps can sometimes be quoted from photos of the existing stat and equipment plate."
      ]
    ],
    "related": [
      "furnace-repair",
      "heat-pumps",
      "emergency-hvac"
    ]
  },
  {
    "slug": "frozen-pipes",
    "category": "residential",
    "nav": "Frozen Pipes & No Heat",
    "h1": "Frozen Pipes & Heating Emergencies",
    "metaTitle": "Frozen Pipes & No-Heat Emergencies Surrey | East Coast AC & Heating",
    "metaDesc": "Frozen pipes after a furnace failure? East Coast AC & Heating restores heat and helps protect plumbing in Surrey and the Lower Mainland. Request emergency service.",
    "image": "van.jpg",
    "heroSub": "When the heat fails in a cold snap, pipes are next. We restore heating and help you deal with frozen-pipe risk tied to a down furnace or boiler.",
    "intro": [
      "A furnace or boiler that dies overnight in a Surrey cold snap can freeze pipes in crawlspaces, garages, and exterior walls. East Coast AC & Heating Ltd treats that as an HVAC emergency: restore heat, reduce further freeze risk, and flag plumbing that needs a plumber if a pipe has already split.",
      "We are an HVAC / plumbing-heating contractor â€” we stay in our lane as HVAC / plumbing-heating, and we will not quote invented thaw-out packages on this website."
    ],
    "bulletsTitle": "How we help",
    "bullets": [
      "No-heat restoration so pipes can thaw safely",
      "Priority dispatch during freeze warnings",
      "Identifying vulnerable piping once heat is back",
      "Temporary heat strategies while parts are sourced",
      "Coordination notes if a plumber is needed for a burst",
      "Advice on keeping heat on during travel",
      "Boiler and furnace emergency repairs",
      "Follow-up once the home is warm"
    ],
    "stepsTitle": "If you think pipes are frozen",
    "steps": [
      [
        "Stay safe",
        "If a pipe has burst, shut the water if you can do it safely. If you smell gas, leave and call 911."
      ],
      [
        "Request emergency HVAC",
        "Use the contact form â€” 778-344-4938 â€” and describe no heat and any frozen or burst pipes."
      ],
      [
        "We restore heat",
        "Heat is what protects the rest of the plumbing."
      ],
      [
        "We tell you the next step",
        "If piping is split, you need a plumber. We will not hide that."
      ]
    ],
    "faqs": [
      [
        "Should I use a torch to thaw pipes?",
        "No. Open flame is a fire and carbon monoxide risk. Restore heat and use safe methods only."
      ],
      [
        "Do you repair burst pipes?",
        "Burst pipe repair is plumbing. We restore the heating system that caused the freeze and will be clear when you need a plumber."
      ],
      [
        "Can space heaters replace a furnace overnight?",
        "Only as a short, carefully watched stopgap. They are not a substitute for a working heating system."
      ]
    ],
    "related": [
      "emergency-hvac",
      "furnace-repair",
      "boilers"
    ]
  },
  {
    "slug": "furnace-safety",
    "category": "residential",
    "nav": "Furnace Smells & CO Safety",
    "h1": "Furnace Smells, Carbon Monoxide & Safety Checks",
    "metaTitle": "Furnace Smell & Carbon Monoxide Safety Surrey | East Coast AC & Heating",
    "metaDesc": "Strange smell from the furnace or a carbon monoxide alarm? East Coast AC & Heating inspects and repairs heating systems in Surrey and the Lower Mainland. Request service.",
    "image": "smoke-detector-installation-surrey.jpg",
    "heroSub": "A strange smell from the furnace is not something to 'wait until Monday.' We inspect combustion, venting, and filters and tell you whether it is dust â€” or a reason to shut the system down.",
    "intro": [
      "Musty, burning, or exhaust-like smells from a furnace worry homeowners for good reason. Sometimes it is dust burning off at first fall start-up. Sometimes it is a cracked heat exchanger, blocked vent, or dirty burner. East Coast AC & Heating Ltd inspects the heating system and does not invent certifications we cannot verify.",
      "If a carbon monoxide alarm sounds, leave the home and call 911. After the emergency services all-clear, we can inspect the furnace or boiler."
    ],
    "bulletsTitle": "Safety checks we perform",
    "bullets": [
      "Strange furnace odour diagnosis",
      "Visual heat-exchanger inspection",
      "Venting and intake review",
      "Flame pattern and burner inspection",
      "Filter and airflow (overheating risk)",
      "Post-CO-alarm equipment inspection",
      "Shut-down recommendations when needed",
      "Repair quotes if a real fault is found"
    ],
    "stepsTitle": "If you smell something from the furnace",
    "steps": [
      [
        "If anyone feels sick or a CO alarm is sounding",
        "Leave immediately and call 911. Do not wait for an HVAC company."
      ],
      [
        "If it is a mild burning-dust smell at first start-up",
        "It can be normal for a short time. If it continues, request service."
      ],
      [
        "We inspect the system",
        "Combustion, venting, and filters â€” not a guess from the driveway."
      ],
      [
        "We recommend repair or shutdown",
        "Safety first. We will not keep a dangerous furnace in service."
      ]
    ],
    "faqs": [
      [
        "Is a burning smell at first fall start-up normal?",
        "A short dusty smell can be. A sulphur, exhaust, or persistent burning smell is not â€” request an inspection."
      ],
      [
        "Do you certify carbon monoxide levels as a lab?",
        "No. We inspect the heating appliance and venting. We do not invent specialized CO-lab certifications."
      ],
      [
        "Should I keep running the furnace if I am unsure?",
        "If you suspect exhaust in the home, shut it down, ventilate, and get help. Comfort is not worth that risk."
      ]
    ],
    "related": [
      "furnace-repair",
      "emergency-hvac",
      "hvac-maintenance"
    ]
  },
  {
    "slug": "commercial-hvac",
    "category": "commercial",
    "nav": "Commercial HVAC",
    "h1": "Commercial Heating & Cooling",
    "metaTitle": "Commercial HVAC Surrey & Lower Mainland | East Coast AC & Heating",
    "metaDesc": "Commercial heating and cooling service for shops, offices and light commercial buildings in Surrey and the Lower Mainland. East Coast AC & Heating. Request a quote.",
    "image": "commercial-hvac-project-surrey.jpg",
    "heroSub": "When a shop or office loses heat or cooling, the business stops. We service light commercial HVAC with the same 24/7 emergency framing as our residential work.",
    "intro": [
      "Retail, offices, shops, and light commercial suites across Surrey need reliable rooftop units, furnaces, and cooling. East Coast AC & Heating Ltd handles service, repair, and replacement quotes for those systems.",
      "We do not list invented commercial rates. After-hours emergencies are quoted before work proceeds."
    ],
    "bulletsTitle": "Commercial HVAC services",
    "bullets": [
      "No-heat / no-cool service calls",
      "Rooftop and packaged unit service",
      "Office and retail comfort repairs",
      "Filter and maintenance programs (quoted)",
      "Equipment replacement quotes",
      "Thermostat and control issues",
      "After-hours emergency response",
      "Coordination with building managers"
    ],
    "stepsTitle": "Working with businesses",
    "steps": [
      [
        "Describe the downtime",
        "Which unit, what failed, and whether customers or staff are affected."
      ],
      [
        "We quote the call",
        "Emergency or scheduled â€” you approve before we start."
      ],
      [
        "Repair with the space in mind",
        "We work around opening hours when the job allows."
      ],
      [
        "Document what we did",
        "So the next visit is not a mystery."
      ]
    ],
    "faqs": [
      [
        "Do you do industrial plants or hospital systems?",
        "We focus on residential and light commercial HVAC. Specialized industrial controls are outside what we claim here."
      ],
      [
        "Can you maintain several sites?",
        "Ask via the contact form. Multi-site work is quoted as a maintenance agreement, not a made-up monthly price on the website."
      ],
      [
        "After-hours commercial service?",
        "Yes â€” request emergency service and describe the building and system."
      ]
    ],
    "related": [
      "emergency-hvac",
      "strata-hvac",
      "hvac-maintenance"
    ]
  },
  {
    "slug": "strata-hvac",
    "category": "commercial",
    "nav": "Strata HVAC",
    "h1": "Strata & Multi-Family HVAC",
    "metaTitle": "Strata HVAC Surrey & Lower Mainland | East Coast AC & Heating",
    "metaDesc": "Strata and multi-family heating and cooling service in Surrey and the Lower Mainland. In-suite and common-area HVAC from East Coast AC & Heating. Request a quote.",
    "image": "team.png",
    "heroSub": "Townhomes, condos, and rental suites have different HVAC access rules. We work with owners and strata on in-suite furnaces, heat pumps, and common-area comfort.",
    "intro": [
      "Multi-family buildings around Metrotown, Surrey City Centre, and New Westminster mix in-suite furnaces, ductless heads, and shared mechanical rooms. East Coast AC & Heating Ltd services the systems we are allowed to work on and coordinates with strata when access or common equipment is involved.",
      "We do not claim we can override strata bylaws. If a job needs council approval, we will say so."
    ],
    "bulletsTitle": "Strata-oriented HVAC",
    "bullets": [
      "In-suite furnace and heat-pump service",
      "Ductless heads in suites and laneways",
      "No-heat / no-cool emergencies",
      "Common-area comfort (quoted after we see it)",
      "Owner-requested replacements",
      "Filter and maintenance for suites",
      "Coordination with building managers",
      "Clear scopes for council quotes"
    ],
    "stepsTitle": "How strata jobs usually run",
    "steps": [
      [
        "Confirm who can authorize the work",
        "Owner, tenant with permission, or strata."
      ],
      [
        "Inspect the actual equipment",
        "In-suite vs common plant is a different quote."
      ],
      [
        "Written scope",
        "So council or the owner can approve without surprises."
      ],
      [
        "Complete and report",
        "What was replaced, what still needs attention."
      ]
    ],
    "faqs": [
      [
        "Can you install a heat pump on a condo balcony?",
        "Sometimes, if the strata allows it and the location is practical. We will not install against bylaws."
      ],
      [
        "Do you service boiler plants for large towers?",
        "Large central plants are quoted only after we confirm the equipment is within what we service. We will not over-claim."
      ],
      [
        "Tenant or owner â€” who should request service?",
        "Whoever is authorized to approve the spend. Have that clear before we dispatch."
      ]
    ],
    "related": [
      "ductless-mini-split",
      "furnace-repair",
      "commercial-hvac"
    ]
  }
];
const LOCATIONS = [
  {
    "slug": "surrey",
    "city": "Surrey",
    "metaTitle": "HVAC Surrey BC | 24/7 Emergency Heating & Cooling | East Coast AC & Heating",
    "metaDesc": "Heating, cooling and 24/7 emergency HVAC in Surrey, BC. Furnace, AC, heat pumps, boilers and mini-splits from East Coast AC & Heating. Request a quote â€” 778-344-4938.",
    "heroSub": "East Coast AC & Heating is based in Surrey. Newton, Guildford, Fleetwood, Cloverdale, South Surrey and Clayton â€” furnace, heat pump, AC and 24/7 no-heat / no-cool service.",
    "intro": [
      "Surrey is home base for East Coast AC & Heating Ltd. Our licence address is 7156 144 St, Unit 18, Surrey, BC. We know the city's housing mix: older Newton and Whalley furnaces, newer Clayton heat pumps, and South Surrey homes that need both heat and cooling.",
      "We cover all of Surrey for emergency heating and cooling, furnace and AC repair, heat pumps, boilers, ductless mini-splits, maintenance, thermostats, frozen-pipe heating emergencies, and furnace-smell / carbon monoxide safety checks."
    ],
    "neighbourhoods": [
      "Whalley / City Centre",
      "Guildford",
      "Newton",
      "Fleetwood",
      "Cloverdale",
      "South Surrey",
      "Panorama Ridge",
      "Grandview Heights",
      "Clayton Heights"
    ],
    "localNote": "Many Surrey homes still run aging mid-efficiency furnaces that struggle on the first cold week of fall. Heat pumps and AC are increasingly common in South Surrey and Clayton.",
    "faqs": [
      [
        "Are you actually based in Surrey?",
        "Yes â€” our 2025 licence address is 7156 144 St, Unit 18, Surrey, BC. We are a local HVAC / plumbing-heating contractor, not a call centre branding itself as local."
      ],
      [
        "How do I reach you in a no-heat emergency?",
        "Call 778-344-4938 or use the contact form. â€” Or use the contact form."
      ]
    ],
    "nearby": [
      "langley",
      "white-rock",
      "delta",
      "new-westminster"
    ]
  },
  {
    "slug": "vancouver",
    "city": "Vancouver",
    "metaTitle": "HVAC Vancouver BC | 24/7 Emergency Heating & Cooling | East Coast AC & Heating",
    "metaDesc": "Heating, cooling and 24/7 emergency HVAC in Vancouver, BC. Furnace, AC, heat pumps, boilers and mini-splits from East Coast AC & Heating. Request a quote â€” 778-344-4938.",
    "heroSub": "East Coast AC & Heating serves Vancouver including Downtown, West End, Kitsilano, Mount Pleasant with furnace, heat pump, air conditioning and 24/7 emergency no-heat / no-cool service.",
    "intro": [
      "Vancouver is part of our regular Lower Mainland coverage. East Coast AC & Heating Ltd repairs and installs furnaces, air conditioners, heat pumps, boilers and ductless mini-splits for homes and light commercial buildings including Downtown, West End, Kitsilano, Mount Pleasant.",
      "When the heat fails or the AC dies, request emergency service through our contact form. We quote before we start and we do not publish invented prices or review counts."
    ],
    "neighbourhoods": [
      "Downtown",
      "West End",
      "Kitsilano",
      "Mount Pleasant",
      "East Vancouver",
      "Commercial Drive",
      "Dunbar",
      "Marpole",
      "Hastings-Sunrise"
    ],
    "localNote": "Vancouver homeowners typically call for no-heat furnace failures, summer AC outages, heat pump service, and seasonal maintenance.",
    "faqs": [
      [
        "Do you serve all of Vancouver?",
        "Yes â€” we provide HVAC service across Vancouver and nearby communities. Confirm your address when you request a quote."
      ],
      [
        "How do I book?",
        "Use the contact form. Call 778-344-4938. â€” Call 778-344-4938."
      ]
    ],
    "nearby": [
      "burnaby",
      "north-vancouver",
      "richmond",
      "new-westminster"
    ]
  },
  {
    "slug": "burnaby",
    "city": "Burnaby",
    "metaTitle": "HVAC Burnaby BC | 24/7 Emergency Heating & Cooling | East Coast AC & Heating",
    "metaDesc": "Heating, cooling and 24/7 emergency HVAC in Burnaby, BC. Furnace, AC, heat pumps, boilers and mini-splits from East Coast AC & Heating. Request a quote â€” 778-344-4938.",
    "heroSub": "East Coast AC & Heating serves Burnaby including Brentwood, Metrotown, Burnaby Heights, North Burnaby with furnace, heat pump, air conditioning and 24/7 emergency no-heat / no-cool service.",
    "intro": [
      "Burnaby is part of our regular Lower Mainland coverage. East Coast AC & Heating Ltd repairs and installs furnaces, air conditioners, heat pumps, boilers and ductless mini-splits for homes and light commercial buildings including Brentwood, Metrotown, Burnaby Heights, North Burnaby.",
      "When the heat fails or the AC dies, request emergency service through our contact form. We quote before we start and we do not publish invented prices or review counts."
    ],
    "neighbourhoods": [
      "Brentwood",
      "Metrotown",
      "Burnaby Heights",
      "North Burnaby",
      "South Burnaby",
      "Edmonds",
      "Capitol Hill",
      "Lougheed",
      "SFU / Burnaby Mountain"
    ],
    "localNote": "Burnaby homeowners typically call for no-heat furnace failures, summer AC outages, heat pump service, and seasonal maintenance.",
    "faqs": [
      [
        "Do you serve all of Burnaby?",
        "Yes â€” we provide HVAC service across Burnaby and nearby communities. Confirm your address when you request a quote."
      ],
      [
        "How do I book?",
        "Use the contact form. Call 778-344-4938. â€” Call 778-344-4938."
      ]
    ],
    "nearby": [
      "vancouver",
      "new-westminster",
      "coquitlam",
      "north-vancouver"
    ]
  },
  {
    "slug": "langley",
    "city": "Langley",
    "metaTitle": "HVAC Langley BC | 24/7 Emergency Heating & Cooling | East Coast AC & Heating",
    "metaDesc": "Heating, cooling and 24/7 emergency HVAC in Langley, BC. Furnace, AC, heat pumps, boilers and mini-splits from East Coast AC & Heating. Request a quote â€” 778-344-4938.",
    "heroSub": "East Coast AC & Heating serves Langley including Willoughby, Walnut Grove, Langley City, Fort Langley with furnace, heat pump, air conditioning and 24/7 emergency no-heat / no-cool service.",
    "intro": [
      "Langley is part of our regular Lower Mainland coverage. East Coast AC & Heating Ltd repairs and installs furnaces, air conditioners, heat pumps, boilers and ductless mini-splits for homes and light commercial buildings including Willoughby, Walnut Grove, Langley City, Fort Langley.",
      "When the heat fails or the AC dies, request emergency service through our contact form. We quote before we start and we do not publish invented prices or review counts."
    ],
    "neighbourhoods": [
      "Willoughby",
      "Walnut Grove",
      "Langley City",
      "Fort Langley",
      "Murrayville",
      "Brookswood",
      "Aldergrove",
      "Fernridge"
    ],
    "localNote": "Langley homeowners typically call for no-heat furnace failures, summer AC outages, heat pump service, and seasonal maintenance.",
    "faqs": [
      [
        "Do you serve all of Langley?",
        "Yes â€” we provide HVAC service across Langley and nearby communities. Confirm your address when you request a quote."
      ],
      [
        "How do I book?",
        "Use the contact form. Call 778-344-4938. â€” Call 778-344-4938."
      ]
    ],
    "nearby": [
      "surrey",
      "abbotsford",
      "maple-ridge",
      "white-rock"
    ]
  },
  {
    "slug": "coquitlam",
    "city": "Coquitlam",
    "metaTitle": "HVAC Coquitlam BC | 24/7 Emergency Heating & Cooling | East Coast AC & Heating",
    "metaDesc": "Heating, cooling and 24/7 emergency HVAC in Coquitlam, BC. Furnace, AC, heat pumps, boilers and mini-splits from East Coast AC & Heating. Request a quote â€” 778-344-4938.",
    "heroSub": "East Coast AC & Heating serves Coquitlam including Burke Mountain, Coquitlam Town Centre, Maillardville, Austin Heights with furnace, heat pump, air conditioning and 24/7 emergency no-heat / no-cool service.",
    "intro": [
      "Coquitlam is part of our regular Lower Mainland coverage. East Coast AC & Heating Ltd repairs and installs furnaces, air conditioners, heat pumps, boilers and ductless mini-splits for homes and light commercial buildings including Burke Mountain, Coquitlam Town Centre, Maillardville, Austin Heights.",
      "When the heat fails or the AC dies, request emergency service through our contact form. We quote before we start and we do not publish invented prices or review counts."
    ],
    "neighbourhoods": [
      "Burke Mountain",
      "Coquitlam Town Centre",
      "Maillardville",
      "Austin Heights",
      "Westwood Plateau",
      "Eagle Ridge",
      "Como Lake",
      "River Springs"
    ],
    "localNote": "Coquitlam homeowners typically call for no-heat furnace failures, summer AC outages, heat pump service, and seasonal maintenance.",
    "faqs": [
      [
        "Do you serve all of Coquitlam?",
        "Yes â€” we provide HVAC service across Coquitlam and nearby communities. Confirm your address when you request a quote."
      ],
      [
        "How do I book?",
        "Use the contact form. Call 778-344-4938. â€” Call 778-344-4938."
      ]
    ],
    "nearby": [
      "port-coquitlam",
      "port-moody",
      "burnaby",
      "new-westminster"
    ]
  },
  {
    "slug": "port-coquitlam",
    "city": "Port Coquitlam",
    "metaTitle": "HVAC Port Coquitlam BC | 24/7 Emergency Heating & Cooling | East Coast AC & Heating",
    "metaDesc": "Heating, cooling and 24/7 emergency HVAC in Port Coquitlam, BC. Furnace, AC, heat pumps, boilers and mini-splits from East Coast AC & Heating. Request a quote â€” 778-344-4938.",
    "heroSub": "East Coast AC & Heating serves Port Coquitlam including Downtown PoCo, Citadel Heights, Mary Hill, Lincoln Park with furnace, heat pump, air conditioning and 24/7 emergency no-heat / no-cool service.",
    "intro": [
      "Port Coquitlam is part of our regular Lower Mainland coverage. East Coast AC & Heating Ltd repairs and installs furnaces, air conditioners, heat pumps, boilers and ductless mini-splits for homes and light commercial buildings including Downtown PoCo, Citadel Heights, Mary Hill, Lincoln Park.",
      "When the heat fails or the AC dies, request emergency service through our contact form. We quote before we start and we do not publish invented prices or review counts."
    ],
    "neighbourhoods": [
      "Downtown PoCo",
      "Citadel Heights",
      "Mary Hill",
      "Lincoln Park",
      "Birchland Manor",
      "Riverwood",
      "Oxford Heights"
    ],
    "localNote": "Port Coquitlam homeowners typically call for no-heat furnace failures, summer AC outages, heat pump service, and seasonal maintenance.",
    "faqs": [
      [
        "Do you serve all of Port Coquitlam?",
        "Yes â€” we provide HVAC service across Port Coquitlam and nearby communities. Confirm your address when you request a quote."
      ],
      [
        "How do I book?",
        "Use the contact form. Call 778-344-4938. â€” Call 778-344-4938."
      ]
    ],
    "nearby": [
      "coquitlam",
      "port-moody",
      "maple-ridge",
      "pitt-meadows"
    ]
  },
  {
    "slug": "port-moody",
    "city": "Port Moody",
    "metaTitle": "HVAC Port Moody BC | 24/7 Emergency Heating & Cooling | East Coast AC & Heating",
    "metaDesc": "Heating, cooling and 24/7 emergency HVAC in Port Moody, BC. Furnace, AC, heat pumps, boilers and mini-splits from East Coast AC & Heating. Request a quote â€” 778-344-4938.",
    "heroSub": "East Coast AC & Heating serves Port Moody including Newport Village, Suter Brook, Heritage Mountain, Heritage Woods with furnace, heat pump, air conditioning and 24/7 emergency no-heat / no-cool service.",
    "intro": [
      "Port Moody is part of our regular Lower Mainland coverage. East Coast AC & Heating Ltd repairs and installs furnaces, air conditioners, heat pumps, boilers and ductless mini-splits for homes and light commercial buildings including Newport Village, Suter Brook, Heritage Mountain, Heritage Woods.",
      "When the heat fails or the AC dies, request emergency service through our contact form. We quote before we start and we do not publish invented prices or review counts."
    ],
    "neighbourhoods": [
      "Newport Village",
      "Suter Brook",
      "Heritage Mountain",
      "Heritage Woods",
      "College Park",
      "Glenayre",
      "Pleasantside"
    ],
    "localNote": "Port Moody homeowners typically call for no-heat furnace failures, summer AC outages, heat pump service, and seasonal maintenance.",
    "faqs": [
      [
        "Do you serve all of Port Moody?",
        "Yes â€” we provide HVAC service across Port Moody and nearby communities. Confirm your address when you request a quote."
      ],
      [
        "How do I book?",
        "Use the contact form. Call 778-344-4938. â€” Call 778-344-4938."
      ]
    ],
    "nearby": [
      "coquitlam",
      "port-coquitlam",
      "burnaby",
      "north-vancouver"
    ]
  },
  {
    "slug": "new-westminster",
    "city": "New Westminster",
    "metaTitle": "HVAC New Westminster BC | 24/7 Emergency Heating & Cooling | East Coast AC & Heating",
    "metaDesc": "Heating, cooling and 24/7 emergency HVAC in New Westminster, BC. Furnace, AC, heat pumps, boilers and mini-splits from East Coast AC & Heating. Request a quote â€” 778-344-4938.",
    "heroSub": "East Coast AC & Heating serves New Westminster including Uptown, Downtown / Quayside, Sapperton, Queens Park with furnace, heat pump, air conditioning and 24/7 emergency no-heat / no-cool service.",
    "intro": [
      "New Westminster is part of our regular Lower Mainland coverage. East Coast AC & Heating Ltd repairs and installs furnaces, air conditioners, heat pumps, boilers and ductless mini-splits for homes and light commercial buildings including Uptown, Downtown / Quayside, Sapperton, Queens Park.",
      "When the heat fails or the AC dies, request emergency service through our contact form. We quote before we start and we do not publish invented prices or review counts."
    ],
    "neighbourhoods": [
      "Uptown",
      "Downtown / Quayside",
      "Sapperton",
      "Queens Park",
      "West End",
      "Connaught Heights",
      "Glenbrooke North",
      "Brow of the Hill"
    ],
    "localNote": "New Westminster homeowners typically call for no-heat furnace failures, summer AC outages, heat pump service, and seasonal maintenance.",
    "faqs": [
      [
        "Do you serve all of New Westminster?",
        "Yes â€” we provide HVAC service across New Westminster and nearby communities. Confirm your address when you request a quote."
      ],
      [
        "How do I book?",
        "Use the contact form. Call 778-344-4938. â€” Call 778-344-4938."
      ]
    ],
    "nearby": [
      "burnaby",
      "coquitlam",
      "surrey",
      "vancouver"
    ]
  },
  {
    "slug": "white-rock",
    "city": "White Rock",
    "metaTitle": "HVAC White Rock BC | 24/7 Emergency Heating & Cooling | East Coast AC & Heating",
    "metaDesc": "Heating, cooling and 24/7 emergency HVAC in White Rock, BC. Furnace, AC, heat pumps, boilers and mini-splits from East Coast AC & Heating. Request a quote â€” 778-344-4938.",
    "heroSub": "East Coast AC & Heating serves White Rock including White Rock Beach / Waterfront, Semiahmoo, Ocean Park, Crescent Beach with furnace, heat pump, air conditioning and 24/7 emergency no-heat / no-cool service.",
    "intro": [
      "White Rock is part of our regular Lower Mainland coverage. East Coast AC & Heating Ltd repairs and installs furnaces, air conditioners, heat pumps, boilers and ductless mini-splits for homes and light commercial buildings including White Rock Beach / Waterfront, Semiahmoo, Ocean Park, Crescent Beach.",
      "When the heat fails or the AC dies, request emergency service through our contact form. We quote before we start and we do not publish invented prices or review counts."
    ],
    "neighbourhoods": [
      "White Rock Beach / Waterfront",
      "Semiahmoo",
      "Ocean Park",
      "Crescent Beach",
      "Five Corners",
      "Hillside"
    ],
    "localNote": "White Rock homeowners typically call for no-heat furnace failures, summer AC outages, heat pump service, and seasonal maintenance.",
    "faqs": [
      [
        "Do you serve all of White Rock?",
        "Yes â€” we provide HVAC service across White Rock and nearby communities. Confirm your address when you request a quote."
      ],
      [
        "How do I book?",
        "Use the contact form. Call 778-344-4938. â€” Call 778-344-4938."
      ]
    ],
    "nearby": [
      "surrey",
      "delta",
      "langley",
      "tsawwassen"
    ]
  },
  {
    "slug": "delta",
    "city": "Delta",
    "metaTitle": "HVAC Delta BC | 24/7 Emergency Heating & Cooling | East Coast AC & Heating",
    "metaDesc": "Heating, cooling and 24/7 emergency HVAC in Delta, BC. Furnace, AC, heat pumps, boilers and mini-splits from East Coast AC & Heating. Request a quote â€” 778-344-4938.",
    "heroSub": "East Coast AC & Heating serves Delta including North Delta, Ladner, Tsawwassen, Sunshine Hills with furnace, heat pump, air conditioning and 24/7 emergency no-heat / no-cool service.",
    "intro": [
      "Delta is part of our regular Lower Mainland coverage. East Coast AC & Heating Ltd repairs and installs furnaces, air conditioners, heat pumps, boilers and ductless mini-splits for homes and light commercial buildings including North Delta, Ladner, Tsawwassen, Sunshine Hills.",
      "When the heat fails or the AC dies, request emergency service through our contact form. We quote before we start and we do not publish invented prices or review counts."
    ],
    "neighbourhoods": [
      "North Delta",
      "Ladner",
      "Tsawwassen",
      "Sunshine Hills",
      "Tilbury",
      "Annieville",
      "Boundary Bay"
    ],
    "localNote": "Delta homeowners typically call for no-heat furnace failures, summer AC outages, heat pump service, and seasonal maintenance.",
    "faqs": [
      [
        "Do you serve all of Delta?",
        "Yes â€” we provide HVAC service across Delta and nearby communities. Confirm your address when you request a quote."
      ],
      [
        "How do I book?",
        "Use the contact form. Call 778-344-4938. â€” Call 778-344-4938."
      ]
    ],
    "nearby": [
      "surrey",
      "tsawwassen",
      "richmond",
      "white-rock"
    ]
  },
  {
    "slug": "richmond",
    "city": "Richmond",
    "metaTitle": "HVAC Richmond BC | 24/7 Emergency Heating & Cooling | East Coast AC & Heating",
    "metaDesc": "Heating, cooling and 24/7 emergency HVAC in Richmond, BC. Furnace, AC, heat pumps, boilers and mini-splits from East Coast AC & Heating. Request a quote â€” 778-344-4938.",
    "heroSub": "East Coast AC & Heating serves Richmond including Steveston, Brighouse / City Centre, Broadmoor, Seafair with furnace, heat pump, air conditioning and 24/7 emergency no-heat / no-cool service.",
    "intro": [
      "Richmond is part of our regular Lower Mainland coverage. East Coast AC & Heating Ltd repairs and installs furnaces, air conditioners, heat pumps, boilers and ductless mini-splits for homes and light commercial buildings including Steveston, Brighouse / City Centre, Broadmoor, Seafair.",
      "When the heat fails or the AC dies, request emergency service through our contact form. We quote before we start and we do not publish invented prices or review counts."
    ],
    "neighbourhoods": [
      "Steveston",
      "Brighouse / City Centre",
      "Broadmoor",
      "Seafair",
      "Hamilton",
      "Thompson",
      "Terra Nova",
      "Ironwood"
    ],
    "localNote": "Richmond homeowners typically call for no-heat furnace failures, summer AC outages, heat pump service, and seasonal maintenance.",
    "faqs": [
      [
        "Do you serve all of Richmond?",
        "Yes â€” we provide HVAC service across Richmond and nearby communities. Confirm your address when you request a quote."
      ],
      [
        "How do I book?",
        "Use the contact form. Call 778-344-4938. â€” Call 778-344-4938."
      ]
    ],
    "nearby": [
      "vancouver",
      "delta",
      "burnaby",
      "new-westminster"
    ]
  },
  {
    "slug": "north-vancouver",
    "city": "North Vancouver",
    "metaTitle": "HVAC North Vancouver BC | 24/7 Emergency Heating & Cooling | East Coast AC & Heating",
    "metaDesc": "Heating, cooling and 24/7 emergency HVAC in North Vancouver, BC. Furnace, AC, heat pumps, boilers and mini-splits from East Coast AC & Heating. Request a quote â€” 778-344-4938.",
    "heroSub": "East Coast AC & Heating serves North Vancouver including Lower Lonsdale, Central Lonsdale, Upper Lonsdale, Lynn Valley with furnace, heat pump, air conditioning and 24/7 emergency no-heat / no-cool service.",
    "intro": [
      "North Vancouver is part of our regular Lower Mainland coverage. East Coast AC & Heating Ltd repairs and installs furnaces, air conditioners, heat pumps, boilers and ductless mini-splits for homes and light commercial buildings including Lower Lonsdale, Central Lonsdale, Upper Lonsdale, Lynn Valley.",
      "When the heat fails or the AC dies, request emergency service through our contact form. We quote before we start and we do not publish invented prices or review counts."
    ],
    "neighbourhoods": [
      "Lower Lonsdale",
      "Central Lonsdale",
      "Upper Lonsdale",
      "Lynn Valley",
      "Deep Cove",
      "Edgemont",
      "Capilano",
      "Seymour"
    ],
    "localNote": "North Vancouver homeowners typically call for no-heat furnace failures, summer AC outages, heat pump service, and seasonal maintenance.",
    "faqs": [
      [
        "Do you serve all of North Vancouver?",
        "Yes â€” we provide HVAC service across North Vancouver and nearby communities. Confirm your address when you request a quote."
      ],
      [
        "How do I book?",
        "Use the contact form. Call 778-344-4938. â€” Call 778-344-4938."
      ]
    ],
    "nearby": [
      "vancouver",
      "burnaby",
      "port-moody",
      "richmond"
    ]
  },
  {
    "slug": "maple-ridge",
    "city": "Maple Ridge",
    "metaTitle": "HVAC Maple Ridge BC | 24/7 Emergency Heating & Cooling | East Coast AC & Heating",
    "metaDesc": "Heating, cooling and 24/7 emergency HVAC in Maple Ridge, BC. Furnace, AC, heat pumps, boilers and mini-splits from East Coast AC & Heating. Request a quote â€” 778-344-4938.",
    "heroSub": "East Coast AC & Heating serves Maple Ridge including Silver Valley, Albion, Hammond, Websters Corners with furnace, heat pump, air conditioning and 24/7 emergency no-heat / no-cool service.",
    "intro": [
      "Maple Ridge is part of our regular Lower Mainland coverage. East Coast AC & Heating Ltd repairs and installs furnaces, air conditioners, heat pumps, boilers and ductless mini-splits for homes and light commercial buildings including Silver Valley, Albion, Hammond, Websters Corners.",
      "When the heat fails or the AC dies, request emergency service through our contact form. We quote before we start and we do not publish invented prices or review counts."
    ],
    "neighbourhoods": [
      "Silver Valley",
      "Albion",
      "Hammond",
      "Websters Corners",
      "Cottonwood",
      "Whonnock",
      "Yennadon",
      "Town Centre"
    ],
    "localNote": "Maple Ridge homeowners typically call for no-heat furnace failures, summer AC outages, heat pump service, and seasonal maintenance.",
    "faqs": [
      [
        "Do you serve all of Maple Ridge?",
        "Yes â€” we provide HVAC service across Maple Ridge and nearby communities. Confirm your address when you request a quote."
      ],
      [
        "How do I book?",
        "Use the contact form. Call 778-344-4938. â€” Call 778-344-4938."
      ]
    ],
    "nearby": [
      "pitt-meadows",
      "port-coquitlam",
      "langley",
      "coquitlam"
    ]
  },
  {
    "slug": "pitt-meadows",
    "city": "Pitt Meadows",
    "metaTitle": "HVAC Pitt Meadows BC | 24/7 Emergency Heating & Cooling | East Coast AC & Heating",
    "metaDesc": "Heating, cooling and 24/7 emergency HVAC in Pitt Meadows, BC. Furnace, AC, heat pumps, boilers and mini-splits from East Coast AC & Heating. Request a quote â€” 778-344-4938.",
    "heroSub": "East Coast AC & Heating serves Pitt Meadows including Town Centre, Bonson, South Bonson, Mid Meadows with furnace, heat pump, air conditioning and 24/7 emergency no-heat / no-cool service.",
    "intro": [
      "Pitt Meadows is part of our regular Lower Mainland coverage. East Coast AC & Heating Ltd repairs and installs furnaces, air conditioners, heat pumps, boilers and ductless mini-splits for homes and light commercial buildings including Town Centre, Bonson, South Bonson, Mid Meadows.",
      "When the heat fails or the AC dies, request emergency service through our contact form. We quote before we start and we do not publish invented prices or review counts."
    ],
    "neighbourhoods": [
      "Town Centre",
      "Bonson",
      "South Bonson",
      "Mid Meadows",
      "Pitt Polder",
      "North Meadows"
    ],
    "localNote": "Pitt Meadows homeowners typically call for no-heat furnace failures, summer AC outages, heat pump service, and seasonal maintenance.",
    "faqs": [
      [
        "Do you serve all of Pitt Meadows?",
        "Yes â€” we provide HVAC service across Pitt Meadows and nearby communities. Confirm your address when you request a quote."
      ],
      [
        "How do I book?",
        "Use the contact form. Call 778-344-4938. â€” Call 778-344-4938."
      ]
    ],
    "nearby": [
      "maple-ridge",
      "port-coquitlam",
      "coquitlam",
      "langley"
    ]
  },
  {
    "slug": "abbotsford",
    "city": "Abbotsford",
    "metaTitle": "HVAC Abbotsford BC | 24/7 Emergency Heating & Cooling | East Coast AC & Heating",
    "metaDesc": "Heating, cooling and 24/7 emergency HVAC in Abbotsford, BC. Furnace, AC, heat pumps, boilers and mini-splits from East Coast AC & Heating. Request a quote â€” 778-344-4938.",
    "heroSub": "East Coast AC & Heating serves Abbotsford including Abbotsford City Centre, Clearbrook, Sumas Mountain, McKee with furnace, heat pump, air conditioning and 24/7 emergency no-heat / no-cool service.",
    "intro": [
      "Abbotsford is part of our regular Lower Mainland coverage. East Coast AC & Heating Ltd repairs and installs furnaces, air conditioners, heat pumps, boilers and ductless mini-splits for homes and light commercial buildings including Abbotsford City Centre, Clearbrook, Sumas Mountain, McKee.",
      "When the heat fails or the AC dies, request emergency service through our contact form. We quote before we start and we do not publish invented prices or review counts."
    ],
    "neighbourhoods": [
      "Abbotsford City Centre",
      "Clearbrook",
      "Sumas Mountain",
      "McKee",
      "Bradner",
      "Matsqui",
      "Mount Lehman",
      "Sandy Hill"
    ],
    "localNote": "Abbotsford homeowners typically call for no-heat furnace failures, summer AC outages, heat pump service, and seasonal maintenance.",
    "faqs": [
      [
        "Do you serve all of Abbotsford?",
        "Yes â€” we provide HVAC service across Abbotsford and nearby communities. Confirm your address when you request a quote."
      ],
      [
        "How do I book?",
        "Use the contact form. Call 778-344-4938. â€” Call 778-344-4938."
      ]
    ],
    "nearby": [
      "langley",
      "surrey",
      "maple-ridge",
      "white-rock"
    ]
  },
  {
    "slug": "tsawwassen",
    "city": "Tsawwassen",
    "metaTitle": "HVAC Tsawwassen BC | 24/7 Emergency Heating & Cooling | East Coast AC & Heating",
    "metaDesc": "Heating, cooling and 24/7 emergency HVAC in Tsawwassen, BC. Furnace, AC, heat pumps, boilers and mini-splits from East Coast AC & Heating. Request a quote â€” 778-344-4938.",
    "heroSub": "East Coast AC & Heating serves Tsawwassen including Tsawwassen Beach, Tsawwassen Shores, Boundary Bay, English Bluff with furnace, heat pump, air conditioning and 24/7 emergency no-heat / no-cool service.",
    "intro": [
      "Tsawwassen is part of our regular Lower Mainland coverage. East Coast AC & Heating Ltd repairs and installs furnaces, air conditioners, heat pumps, boilers and ductless mini-splits for homes and light commercial buildings including Tsawwassen Beach, Tsawwassen Shores, Boundary Bay, English Bluff.",
      "When the heat fails or the AC dies, request emergency service through our contact form. We quote before we start and we do not publish invented prices or review counts."
    ],
    "neighbourhoods": [
      "Tsawwassen Beach",
      "Tsawwassen Shores",
      "Boundary Bay",
      "English Bluff",
      "Pebble Hill",
      "Cliff Drive"
    ],
    "localNote": "Tsawwassen homeowners typically call for no-heat furnace failures, summer AC outages, heat pump service, and seasonal maintenance.",
    "faqs": [
      [
        "Do you serve all of Tsawwassen?",
        "Yes â€” we provide HVAC service across Tsawwassen and nearby communities. Confirm your address when you request a quote."
      ],
      [
        "How do I book?",
        "Use the contact form. Call 778-344-4938. â€” Call 778-344-4938."
      ]
    ],
    "nearby": [
      "delta",
      "richmond",
      "white-rock",
      "surrey"
    ]
  }
];
const NEIGHBOURHOODS = [
  {
    "slug": "newton-surrey",
    "name": "Newton",
    "parent": "surrey",
    "blurb": "Newton homeowners call East Coast AC & Heating for furnace, heat pump, and air conditioning service â€” including 24/7 emergency no-heat and no-cool calls."
  },
  {
    "slug": "guildford-surrey",
    "name": "Guildford",
    "parent": "surrey",
    "blurb": "Guildford homeowners call East Coast AC & Heating for furnace, heat pump, and air conditioning service â€” including 24/7 emergency no-heat and no-cool calls."
  },
  {
    "slug": "fleetwood-surrey",
    "name": "Fleetwood",
    "parent": "surrey",
    "blurb": "Fleetwood homeowners call East Coast AC & Heating for furnace, heat pump, and air conditioning service â€” including 24/7 emergency no-heat and no-cool calls."
  },
  {
    "slug": "cloverdale-surrey",
    "name": "Cloverdale",
    "parent": "surrey",
    "blurb": "Cloverdale homeowners call East Coast AC & Heating for furnace, heat pump, and air conditioning service â€” including 24/7 emergency no-heat and no-cool calls."
  },
  {
    "slug": "south-surrey",
    "name": "South Surrey",
    "parent": "surrey",
    "blurb": "South Surrey homeowners call East Coast AC & Heating for furnace, heat pump, and air conditioning service â€” including 24/7 emergency no-heat and no-cool calls."
  },
  {
    "slug": "whalley-surrey",
    "name": "Whalley / City Centre",
    "parent": "surrey",
    "blurb": "Whalley / City Centre homeowners call East Coast AC & Heating for furnace, heat pump, and air conditioning service â€” including 24/7 emergency no-heat and no-cool calls."
  },
  {
    "slug": "panorama-ridge-surrey",
    "name": "Panorama Ridge",
    "parent": "surrey",
    "blurb": "Panorama Ridge homeowners call East Coast AC & Heating for furnace, heat pump, and air conditioning service â€” including 24/7 emergency no-heat and no-cool calls."
  },
  {
    "slug": "clayton-surrey",
    "name": "Clayton Heights",
    "parent": "surrey",
    "blurb": "Clayton Heights homeowners call East Coast AC & Heating for furnace, heat pump, and air conditioning service â€” including 24/7 emergency no-heat and no-cool calls."
  },
  {
    "slug": "kitsilano-vancouver",
    "name": "Kitsilano",
    "parent": "vancouver",
    "blurb": "Kitsilano homeowners call East Coast AC & Heating for furnace, heat pump, and air conditioning service â€” including 24/7 emergency no-heat and no-cool calls."
  },
  {
    "slug": "east-vancouver",
    "name": "East Vancouver",
    "parent": "vancouver",
    "blurb": "East Vancouver homeowners call East Coast AC & Heating for furnace, heat pump, and air conditioning service â€” including 24/7 emergency no-heat and no-cool calls."
  },
  {
    "slug": "mount-pleasant-vancouver",
    "name": "Mount Pleasant",
    "parent": "vancouver",
    "blurb": "Mount Pleasant homeowners call East Coast AC & Heating for furnace, heat pump, and air conditioning service â€” including 24/7 emergency no-heat and no-cool calls."
  },
  {
    "slug": "dunbar-vancouver",
    "name": "Dunbar",
    "parent": "vancouver",
    "blurb": "Dunbar homeowners call East Coast AC & Heating for furnace, heat pump, and air conditioning service â€” including 24/7 emergency no-heat and no-cool calls."
  },
  {
    "slug": "downtown-vancouver",
    "name": "Downtown Vancouver",
    "parent": "vancouver",
    "blurb": "Downtown Vancouver homeowners call East Coast AC & Heating for furnace, heat pump, and air conditioning service â€” including 24/7 emergency no-heat and no-cool calls."
  },
  {
    "slug": "marpole-vancouver",
    "name": "Marpole",
    "parent": "vancouver",
    "blurb": "Marpole homeowners call East Coast AC & Heating for furnace, heat pump, and air conditioning service â€” including 24/7 emergency no-heat and no-cool calls."
  },
  {
    "slug": "metrotown-burnaby",
    "name": "Metrotown",
    "parent": "burnaby",
    "blurb": "Metrotown homeowners call East Coast AC & Heating for furnace, heat pump, and air conditioning service â€” including 24/7 emergency no-heat and no-cool calls."
  },
  {
    "slug": "brentwood-burnaby",
    "name": "Brentwood",
    "parent": "burnaby",
    "blurb": "Brentwood homeowners call East Coast AC & Heating for furnace, heat pump, and air conditioning service â€” including 24/7 emergency no-heat and no-cool calls."
  },
  {
    "slug": "burnaby-heights",
    "name": "Burnaby Heights",
    "parent": "burnaby",
    "blurb": "Burnaby Heights homeowners call East Coast AC & Heating for furnace, heat pump, and air conditioning service â€” including 24/7 emergency no-heat and no-cool calls."
  },
  {
    "slug": "north-burnaby",
    "name": "North Burnaby",
    "parent": "burnaby",
    "blurb": "North Burnaby homeowners call East Coast AC & Heating for furnace, heat pump, and air conditioning service â€” including 24/7 emergency no-heat and no-cool calls."
  },
  {
    "slug": "south-burnaby",
    "name": "South Burnaby",
    "parent": "burnaby",
    "blurb": "South Burnaby homeowners call East Coast AC & Heating for furnace, heat pump, and air conditioning service â€” including 24/7 emergency no-heat and no-cool calls."
  },
  {
    "slug": "edmonds-burnaby",
    "name": "Edmonds",
    "parent": "burnaby",
    "blurb": "Edmonds homeowners call East Coast AC & Heating for furnace, heat pump, and air conditioning service â€” including 24/7 emergency no-heat and no-cool calls."
  },
  {
    "slug": "willoughby-langley",
    "name": "Willoughby",
    "parent": "langley",
    "blurb": "Willoughby homeowners call East Coast AC & Heating for furnace, heat pump, and air conditioning service â€” including 24/7 emergency no-heat and no-cool calls."
  },
  {
    "slug": "walnut-grove-langley",
    "name": "Walnut Grove",
    "parent": "langley",
    "blurb": "Walnut Grove homeowners call East Coast AC & Heating for furnace, heat pump, and air conditioning service â€” including 24/7 emergency no-heat and no-cool calls."
  },
  {
    "slug": "fort-langley",
    "name": "Fort Langley",
    "parent": "langley",
    "blurb": "Fort Langley homeowners call East Coast AC & Heating for furnace, heat pump, and air conditioning service â€” including 24/7 emergency no-heat and no-cool calls."
  },
  {
    "slug": "brookswood-langley",
    "name": "Brookswood",
    "parent": "langley",
    "blurb": "Brookswood homeowners call East Coast AC & Heating for furnace, heat pump, and air conditioning service â€” including 24/7 emergency no-heat and no-cool calls."
  },
  {
    "slug": "aldergrove-langley",
    "name": "Aldergrove",
    "parent": "langley",
    "blurb": "Aldergrove homeowners call East Coast AC & Heating for furnace, heat pump, and air conditioning service â€” including 24/7 emergency no-heat and no-cool calls."
  },
  {
    "slug": "murrayville-langley",
    "name": "Murrayville",
    "parent": "langley",
    "blurb": "Murrayville homeowners call East Coast AC & Heating for furnace, heat pump, and air conditioning service â€” including 24/7 emergency no-heat and no-cool calls."
  },
  {
    "slug": "burke-mountain-coquitlam",
    "name": "Burke Mountain",
    "parent": "coquitlam",
    "blurb": "Burke Mountain homeowners call East Coast AC & Heating for furnace, heat pump, and air conditioning service â€” including 24/7 emergency no-heat and no-cool calls."
  },
  {
    "slug": "maillardville-coquitlam",
    "name": "Maillardville",
    "parent": "coquitlam",
    "blurb": "Maillardville homeowners call East Coast AC & Heating for furnace, heat pump, and air conditioning service â€” including 24/7 emergency no-heat and no-cool calls."
  },
  {
    "slug": "westwood-plateau-coquitlam",
    "name": "Westwood Plateau",
    "parent": "coquitlam",
    "blurb": "Westwood Plateau homeowners call East Coast AC & Heating for furnace, heat pump, and air conditioning service â€” including 24/7 emergency no-heat and no-cool calls."
  },
  {
    "slug": "coquitlam-town-centre",
    "name": "Coquitlam Town Centre",
    "parent": "coquitlam",
    "blurb": "Coquitlam Town Centre homeowners call East Coast AC & Heating for furnace, heat pump, and air conditioning service â€” including 24/7 emergency no-heat and no-cool calls."
  },
  {
    "slug": "austin-heights-coquitlam",
    "name": "Austin Heights",
    "parent": "coquitlam",
    "blurb": "Austin Heights homeowners call East Coast AC & Heating for furnace, heat pump, and air conditioning service â€” including 24/7 emergency no-heat and no-cool calls."
  },
  {
    "slug": "downtown-port-coquitlam",
    "name": "Downtown PoCo",
    "parent": "port-coquitlam",
    "blurb": "Downtown PoCo homeowners call East Coast AC & Heating for furnace, heat pump, and air conditioning service â€” including 24/7 emergency no-heat and no-cool calls."
  },
  {
    "slug": "citadel-heights-port-coquitlam",
    "name": "Citadel Heights",
    "parent": "port-coquitlam",
    "blurb": "Citadel Heights homeowners call East Coast AC & Heating for furnace, heat pump, and air conditioning service â€” including 24/7 emergency no-heat and no-cool calls."
  },
  {
    "slug": "mary-hill-port-coquitlam",
    "name": "Mary Hill",
    "parent": "port-coquitlam",
    "blurb": "Mary Hill homeowners call East Coast AC & Heating for furnace, heat pump, and air conditioning service â€” including 24/7 emergency no-heat and no-cool calls."
  },
  {
    "slug": "riverwood-port-coquitlam",
    "name": "Riverwood",
    "parent": "port-coquitlam",
    "blurb": "Riverwood homeowners call East Coast AC & Heating for furnace, heat pump, and air conditioning service â€” including 24/7 emergency no-heat and no-cool calls."
  },
  {
    "slug": "oxford-heights-port-coquitlam",
    "name": "Oxford Heights",
    "parent": "port-coquitlam",
    "blurb": "Oxford Heights homeowners call East Coast AC & Heating for furnace, heat pump, and air conditioning service â€” including 24/7 emergency no-heat and no-cool calls."
  },
  {
    "slug": "newport-village-port-moody",
    "name": "Newport Village",
    "parent": "port-moody",
    "blurb": "Newport Village homeowners call East Coast AC & Heating for furnace, heat pump, and air conditioning service â€” including 24/7 emergency no-heat and no-cool calls."
  },
  {
    "slug": "suter-brook-port-moody",
    "name": "Suter Brook",
    "parent": "port-moody",
    "blurb": "Suter Brook homeowners call East Coast AC & Heating for furnace, heat pump, and air conditioning service â€” including 24/7 emergency no-heat and no-cool calls."
  },
  {
    "slug": "heritage-mountain-port-moody",
    "name": "Heritage Mountain",
    "parent": "port-moody",
    "blurb": "Heritage Mountain homeowners call East Coast AC & Heating for furnace, heat pump, and air conditioning service â€” including 24/7 emergency no-heat and no-cool calls."
  },
  {
    "slug": "heritage-woods-port-moody",
    "name": "Heritage Woods",
    "parent": "port-moody",
    "blurb": "Heritage Woods homeowners call East Coast AC & Heating for furnace, heat pump, and air conditioning service â€” including 24/7 emergency no-heat and no-cool calls."
  },
  {
    "slug": "college-park-port-moody",
    "name": "College Park",
    "parent": "port-moody",
    "blurb": "College Park homeowners call East Coast AC & Heating for furnace, heat pump, and air conditioning service â€” including 24/7 emergency no-heat and no-cool calls."
  },
  {
    "slug": "queens-park-new-westminster",
    "name": "Queens Park",
    "parent": "new-westminster",
    "blurb": "Queens Park homeowners call East Coast AC & Heating for furnace, heat pump, and air conditioning service â€” including 24/7 emergency no-heat and no-cool calls."
  },
  {
    "slug": "sapperton-new-westminster",
    "name": "Sapperton",
    "parent": "new-westminster",
    "blurb": "Sapperton homeowners call East Coast AC & Heating for furnace, heat pump, and air conditioning service â€” including 24/7 emergency no-heat and no-cool calls."
  },
  {
    "slug": "uptown-new-westminster",
    "name": "Uptown",
    "parent": "new-westminster",
    "blurb": "Uptown homeowners call East Coast AC & Heating for furnace, heat pump, and air conditioning service â€” including 24/7 emergency no-heat and no-cool calls."
  },
  {
    "slug": "quayside-new-westminster",
    "name": "Quayside / Downtown",
    "parent": "new-westminster",
    "blurb": "Quayside / Downtown homeowners call East Coast AC & Heating for furnace, heat pump, and air conditioning service â€” including 24/7 emergency no-heat and no-cool calls."
  },
  {
    "slug": "west-end-new-westminster",
    "name": "West End",
    "parent": "new-westminster",
    "blurb": "West End homeowners call East Coast AC & Heating for furnace, heat pump, and air conditioning service â€” including 24/7 emergency no-heat and no-cool calls."
  },
  {
    "slug": "white-rock-beach",
    "name": "White Rock Beach",
    "parent": "white-rock",
    "blurb": "White Rock Beach homeowners call East Coast AC & Heating for furnace, heat pump, and air conditioning service â€” including 24/7 emergency no-heat and no-cool calls."
  },
  {
    "slug": "semiahmoo-white-rock",
    "name": "Semiahmoo",
    "parent": "white-rock",
    "blurb": "Semiahmoo homeowners call East Coast AC & Heating for furnace, heat pump, and air conditioning service â€” including 24/7 emergency no-heat and no-cool calls."
  },
  {
    "slug": "ocean-park-white-rock",
    "name": "Ocean Park",
    "parent": "white-rock",
    "blurb": "Ocean Park homeowners call East Coast AC & Heating for furnace, heat pump, and air conditioning service â€” including 24/7 emergency no-heat and no-cool calls."
  },
  {
    "slug": "crescent-beach-white-rock",
    "name": "Crescent Beach",
    "parent": "white-rock",
    "blurb": "Crescent Beach homeowners call East Coast AC & Heating for furnace, heat pump, and air conditioning service â€” including 24/7 emergency no-heat and no-cool calls."
  },
  {
    "slug": "north-delta",
    "name": "North Delta",
    "parent": "delta",
    "blurb": "North Delta homeowners call East Coast AC & Heating for furnace, heat pump, and air conditioning service â€” including 24/7 emergency no-heat and no-cool calls."
  },
  {
    "slug": "ladner-delta",
    "name": "Ladner",
    "parent": "delta",
    "blurb": "Ladner homeowners call East Coast AC & Heating for furnace, heat pump, and air conditioning service â€” including 24/7 emergency no-heat and no-cool calls."
  },
  {
    "slug": "sunshine-hills-delta",
    "name": "Sunshine Hills",
    "parent": "delta",
    "blurb": "Sunshine Hills homeowners call East Coast AC & Heating for furnace, heat pump, and air conditioning service â€” including 24/7 emergency no-heat and no-cool calls."
  },
  {
    "slug": "annieville-delta",
    "name": "Annieville",
    "parent": "delta",
    "blurb": "Annieville homeowners call East Coast AC & Heating for furnace, heat pump, and air conditioning service â€” including 24/7 emergency no-heat and no-cool calls."
  },
  {
    "slug": "boundary-bay-delta",
    "name": "Boundary Bay",
    "parent": "delta",
    "blurb": "Boundary Bay homeowners call East Coast AC & Heating for furnace, heat pump, and air conditioning service â€” including 24/7 emergency no-heat and no-cool calls."
  },
  {
    "slug": "steveston-richmond",
    "name": "Steveston",
    "parent": "richmond",
    "blurb": "Steveston homeowners call East Coast AC & Heating for furnace, heat pump, and air conditioning service â€” including 24/7 emergency no-heat and no-cool calls."
  },
  {
    "slug": "brighouse-richmond",
    "name": "Brighouse / City Centre",
    "parent": "richmond",
    "blurb": "Brighouse / City Centre homeowners call East Coast AC & Heating for furnace, heat pump, and air conditioning service â€” including 24/7 emergency no-heat and no-cool calls."
  },
  {
    "slug": "broadmoor-richmond",
    "name": "Broadmoor",
    "parent": "richmond",
    "blurb": "Broadmoor homeowners call East Coast AC & Heating for furnace, heat pump, and air conditioning service â€” including 24/7 emergency no-heat and no-cool calls."
  },
  {
    "slug": "seafair-richmond",
    "name": "Seafair",
    "parent": "richmond",
    "blurb": "Seafair homeowners call East Coast AC & Heating for furnace, heat pump, and air conditioning service â€” including 24/7 emergency no-heat and no-cool calls."
  },
  {
    "slug": "terra-nova-richmond",
    "name": "Terra Nova",
    "parent": "richmond",
    "blurb": "Terra Nova homeowners call East Coast AC & Heating for furnace, heat pump, and air conditioning service â€” including 24/7 emergency no-heat and no-cool calls."
  },
  {
    "slug": "lonsdale-north-vancouver",
    "name": "Lonsdale",
    "parent": "north-vancouver",
    "blurb": "Lonsdale homeowners call East Coast AC & Heating for furnace, heat pump, and air conditioning service â€” including 24/7 emergency no-heat and no-cool calls."
  },
  {
    "slug": "lynn-valley-north-vancouver",
    "name": "Lynn Valley",
    "parent": "north-vancouver",
    "blurb": "Lynn Valley homeowners call East Coast AC & Heating for furnace, heat pump, and air conditioning service â€” including 24/7 emergency no-heat and no-cool calls."
  },
  {
    "slug": "deep-cove-north-vancouver",
    "name": "Deep Cove",
    "parent": "north-vancouver",
    "blurb": "Deep Cove homeowners call East Coast AC & Heating for furnace, heat pump, and air conditioning service â€” including 24/7 emergency no-heat and no-cool calls."
  },
  {
    "slug": "edgemont-north-vancouver",
    "name": "Edgemont",
    "parent": "north-vancouver",
    "blurb": "Edgemont homeowners call East Coast AC & Heating for furnace, heat pump, and air conditioning service â€” including 24/7 emergency no-heat and no-cool calls."
  },
  {
    "slug": "seymour-north-vancouver",
    "name": "Seymour",
    "parent": "north-vancouver",
    "blurb": "Seymour homeowners call East Coast AC & Heating for furnace, heat pump, and air conditioning service â€” including 24/7 emergency no-heat and no-cool calls."
  },
  {
    "slug": "silver-valley-maple-ridge",
    "name": "Silver Valley",
    "parent": "maple-ridge",
    "blurb": "Silver Valley homeowners call East Coast AC & Heating for furnace, heat pump, and air conditioning service â€” including 24/7 emergency no-heat and no-cool calls."
  },
  {
    "slug": "albion-maple-ridge",
    "name": "Albion",
    "parent": "maple-ridge",
    "blurb": "Albion homeowners call East Coast AC & Heating for furnace, heat pump, and air conditioning service â€” including 24/7 emergency no-heat and no-cool calls."
  },
  {
    "slug": "hammond-maple-ridge",
    "name": "Hammond",
    "parent": "maple-ridge",
    "blurb": "Hammond homeowners call East Coast AC & Heating for furnace, heat pump, and air conditioning service â€” including 24/7 emergency no-heat and no-cool calls."
  },
  {
    "slug": "cottonwood-maple-ridge",
    "name": "Cottonwood",
    "parent": "maple-ridge",
    "blurb": "Cottonwood homeowners call East Coast AC & Heating for furnace, heat pump, and air conditioning service â€” including 24/7 emergency no-heat and no-cool calls."
  },
  {
    "slug": "websters-corners-maple-ridge",
    "name": "Websters Corners",
    "parent": "maple-ridge",
    "blurb": "Websters Corners homeowners call East Coast AC & Heating for furnace, heat pump, and air conditioning service â€” including 24/7 emergency no-heat and no-cool calls."
  },
  {
    "slug": "bonson-pitt-meadows",
    "name": "Bonson",
    "parent": "pitt-meadows",
    "blurb": "Bonson homeowners call East Coast AC & Heating for furnace, heat pump, and air conditioning service â€” including 24/7 emergency no-heat and no-cool calls."
  },
  {
    "slug": "mid-meadows-pitt-meadows",
    "name": "Mid Meadows",
    "parent": "pitt-meadows",
    "blurb": "Mid Meadows homeowners call East Coast AC & Heating for furnace, heat pump, and air conditioning service â€” including 24/7 emergency no-heat and no-cool calls."
  },
  {
    "slug": "north-meadows-pitt-meadows",
    "name": "North Meadows",
    "parent": "pitt-meadows",
    "blurb": "North Meadows homeowners call East Coast AC & Heating for furnace, heat pump, and air conditioning service â€” including 24/7 emergency no-heat and no-cool calls."
  },
  {
    "slug": "pitt-polder-pitt-meadows",
    "name": "Pitt Polder",
    "parent": "pitt-meadows",
    "blurb": "Pitt Polder homeowners call East Coast AC & Heating for furnace, heat pump, and air conditioning service â€” including 24/7 emergency no-heat and no-cool calls."
  },
  {
    "slug": "clearbrook-abbotsford",
    "name": "Clearbrook",
    "parent": "abbotsford",
    "blurb": "Clearbrook homeowners call East Coast AC & Heating for furnace, heat pump, and air conditioning service â€” including 24/7 emergency no-heat and no-cool calls."
  },
  {
    "slug": "abbotsford-city-centre",
    "name": "Abbotsford City Centre",
    "parent": "abbotsford",
    "blurb": "Abbotsford City Centre homeowners call East Coast AC & Heating for furnace, heat pump, and air conditioning service â€” including 24/7 emergency no-heat and no-cool calls."
  },
  {
    "slug": "matsqui-abbotsford",
    "name": "Matsqui",
    "parent": "abbotsford",
    "blurb": "Matsqui homeowners call East Coast AC & Heating for furnace, heat pump, and air conditioning service â€” including 24/7 emergency no-heat and no-cool calls."
  },
  {
    "slug": "bradner-abbotsford",
    "name": "Bradner",
    "parent": "abbotsford",
    "blurb": "Bradner homeowners call East Coast AC & Heating for furnace, heat pump, and air conditioning service â€” including 24/7 emergency no-heat and no-cool calls."
  },
  {
    "slug": "mount-lehman-abbotsford",
    "name": "Mount Lehman",
    "parent": "abbotsford",
    "blurb": "Mount Lehman homeowners call East Coast AC & Heating for furnace, heat pump, and air conditioning service â€” including 24/7 emergency no-heat and no-cool calls."
  },
  {
    "slug": "tsawwassen-beach",
    "name": "Tsawwassen Beach",
    "parent": "tsawwassen",
    "blurb": "Tsawwassen Beach homeowners call East Coast AC & Heating for furnace, heat pump, and air conditioning service â€” including 24/7 emergency no-heat and no-cool calls."
  },
  {
    "slug": "tsawwassen-shores",
    "name": "Tsawwassen Shores",
    "parent": "tsawwassen",
    "blurb": "Tsawwassen Shores homeowners call East Coast AC & Heating for furnace, heat pump, and air conditioning service â€” including 24/7 emergency no-heat and no-cool calls."
  },
  {
    "slug": "english-bluff-tsawwassen",
    "name": "English Bluff",
    "parent": "tsawwassen",
    "blurb": "English Bluff homeowners call East Coast AC & Heating for furnace, heat pump, and air conditioning service â€” including 24/7 emergency no-heat and no-cool calls."
  },
  {
    "slug": "pebble-hill-tsawwassen",
    "name": "Pebble Hill",
    "parent": "tsawwassen",
    "blurb": "Pebble Hill homeowners call East Coast AC & Heating for furnace, heat pump, and air conditioning service â€” including 24/7 emergency no-heat and no-cool calls."
  }
];
const BLOG = [
  {
    "slug": "no-heat-furnace-wont-start",
    "title": "Furnace Will Not Start: What to Check Before You Panic",
    "metaTitle": "Furnace Won't Start | No-Heat Guide | East Coast AC & Heating",
    "metaDesc": "Furnace will not start on a cold Surrey morning? A calm checklist from East Coast AC & Heating â€” then request service if heat is still out.",
    "date": "2026-08-25",
    "read": "5 min read",
    "summary": "A practical no-heat checklist for Lower Mainland homeowners: thermostat, filter, switch, and when to stop DIY and request HVAC service.",
    "body": [
      {
        "h": null,
        "p": [
          "A cold house with a silent furnace is stressful. Some checks are safe. Some are not. Here is a calm order of operations for Surrey and Lower Mainland homes."
        ]
      },
      {
        "h": "Check the thermostat first",
        "p": [
          "Make sure it is set to heat and the set-point is above room temperature. Blank display? Try fresh batteries. A heat-pump thermostat stuck on cool will not call for heat."
        ]
      },
      {
        "h": "Filter and the furnace switch",
        "p": [
          "A clogged filter can cause a limit trip. The furnace switch looks like a light switch â€” confirm it is on. If the furnace still has no power after the switch, stop and request service rather than repeating resets."
        ]
      },
      {
        "h": "Gas and carbon monoxide",
        "p": [
          "If you smell gas, leave and call 911. If a carbon monoxide alarm sounds, leave and call 911. Do not keep resetting a furnace that smells like exhaust."
        ]
      },
      {
        "h": "When to request service",
        "p": [
          "If the furnace tries to start and shuts down, or nothing happens after the safe checks, request emergency HVAC through our contact form. Call 778-344-4938."
        ]
      }
    ],
    "faqs": [
      [
        "Should I keep hitting reset?",
        "No. Repeated lockouts usually mean a real fault â€” igniter, flame sensor, vent, or control."
      ],
      [
        "Can a dirty filter really stop heat?",
        "Yes. Restricted airflow overheats the furnace and the safety limit opens."
      ]
    ],
    "related": [
      "emergency-hvac",
      "furnace-repair"
    ]
  },
  {
    "slug": "ac-not-cooling-summer",
    "title": "AC Not Cooling: What Usually Failed (and What Can Wait)",
    "metaTitle": "AC Not Cooling in Summer | East Coast AC & Heating",
    "metaDesc": "Air conditioner running but not cooling? East Coast AC & Heating explains common Lower Mainland no-cool causes â€” without invented repair prices.",
    "date": "2026-08-25",
    "read": "5 min read",
    "summary": "Why an AC runs without cooling, what you can safely check, and when to request repair in a heat wave.",
    "body": [
      {
        "h": null,
        "p": [
          "An outdoor fan spinning does not mean you have cooling. Lower Mainland heat waves expose neglected condensers, failed capacitors, and undersized systems."
        ]
      },
      {
        "h": "Safe things to check",
        "p": [
          "Thermostat in cool, set below room temperature. Filter not clogged. Outdoor unit free of debris and standing water. Breaker not tripped."
        ]
      },
      {
        "h": "Common failures",
        "p": [
          "Capacitors, contactors, outdoor fan motors, dirty coils, and low refrigerant from a leak. Refrigerant is not a 'top up' product â€” a leak needs a repair."
        ]
      },
      {
        "h": "Repair vs replace",
        "p": [
          "We quote both when the system is old enough that a compressor repair is a poor spend. No invented prices on this page â€” you get a written quote."
        ]
      }
    ],
    "faqs": [
      [
        "Can I add refrigerant myself?",
        "No. That is regulated work and usually hides a leak."
      ],
      [
        "Heat pump or AC â€” does this apply?",
        "Yes. Cooling mode failures look similar on both."
      ]
    ],
    "related": [
      "ac-repair",
      "heat-pumps"
    ]
  },
  {
    "slug": "heat-pumps-lower-mainland",
    "title": "Heat Pumps in the Lower Mainland: When They Make Sense",
    "metaTitle": "Heat Pumps in Surrey & the Lower Mainland | East Coast AC & Heating",
    "metaDesc": "When a heat pump is a good fit for a Surrey or Vancouver home, when furnace backup still matters, and how East Coast AC & Heating quotes installs.",
    "date": "2026-08-25",
    "read": "6 min read",
    "summary": "A straight explanation of ducted vs ductless heat pumps for coastal BC weather â€” no rebate amounts we cannot verify.",
    "body": [
      {
        "h": null,
        "p": [
          "Most of the Lower Mainland winter is mild enough that a modern heat pump handles heating and still gives you summer cooling. That is the appeal."
        ]
      },
      {
        "h": "Ducted vs ductless",
        "p": [
          "If you have decent ducts and a furnace, a ducted heat pump (sometimes with furnace backup) is often the cleanest upgrade. No ducts? Mini-splits target the rooms you actually use."
        ]
      },
      {
        "h": "Backup heat",
        "p": [
          "Some homes still want a gas furnace for the coldest nights. That is a design choice, not a sales trick. We will say if your home needs it."
        ]
      },
      {
        "h": "Rebates",
        "p": [
          "Provincial and federal programs change. We will not print dollar amounts that might be wrong next month. Ask when you request a quote."
        ]
      }
    ],
    "faqs": [
      [
        "Will I still need a furnace?",
        "Sometimes. It depends on the home, the heat pump, and how you want the coldest week to feel."
      ],
      [
        "Can you install in a strata unit?",
        "Only if the strata allows the outdoor unit location. We will not install against bylaws."
      ]
    ],
    "related": [
      "heat-pumps",
      "ductless-mini-split"
    ]
  },
  {
    "slug": "strange-furnace-smells",
    "title": "Strange Smell from the Furnace: Dust, Filter, or Get Out",
    "metaTitle": "Strange Furnace Smell | Carbon Monoxide Caution | East Coast AC & Heating",
    "metaDesc": "Burning, musty, or exhaust smells from a furnace? What can wait, what cannot, and when to leave the home. From East Coast AC & Heating in Surrey.",
    "date": "2026-08-25",
    "read": "5 min read",
    "summary": "How to tell a dusty first-start smell from a furnace that should be shut down â€” including carbon monoxide caution.",
    "body": [
      {
        "h": null,
        "p": [
          "Fall start-up smells scare people, and some of those scares are justified. This is a safety topic, not a sales page."
        ]
      },
      {
        "h": "Dusty burning at first start",
        "p": [
          "Dust on the heat exchanger can smell for a short time when heat is first used. If it fades, it was likely dust. If it continues, request an inspection."
        ]
      },
      {
        "h": "Musty or dirty-sock smells",
        "p": [
          "Often a filter, coil, or moisture issue. Unpleasant, usually not an evacuate-now emergency, but still worth service."
        ]
      },
      {
        "h": "Exhaust, sulphur, or CO alarm",
        "p": [
          "Leave the home. Call 911. After you are safe, we can inspect the furnace and venting. We do not invent lab certifications."
        ]
      }
    ],
    "faqs": [
      [
        "Should I run the furnace to 'clear the smell'?",
        "Not if you suspect exhaust or feel unwell."
      ],
      [
        "Do you replace CO alarms?",
        "We inspect heating appliances. Alarm hardware is a separate home-safety item â€” follow the manufacturer's replacement date."
      ]
    ],
    "related": [
      "furnace-safety",
      "furnace-repair"
    ]
  },
  {
    "slug": "hvac-maintenance-fall-spring",
    "title": "Why Fall Furnace and Spring AC Checks Matter in BC",
    "metaTitle": "HVAC Maintenance in BC | Fall & Spring Checks | East Coast AC & Heating",
    "metaDesc": "Seasonal furnace and AC maintenance for Surrey and the Lower Mainland â€” what we actually check, without membership scare tactics.",
    "date": "2026-08-25",
    "read": "4 min read",
    "summary": "What a real maintenance visit includes, and why the first cold Friday night is the wrong time to find a failed igniter.",
    "body": [
      {
        "h": null,
        "p": [
          "The first cold snap and the first heat wave are when neglected systems fail. A seasonal check is cheaper than an emergency on a long weekend â€” though we will not invent a dollar comparison here."
        ]
      },
      {
        "h": "Fall (heat)",
        "p": [
          "Igniter, flame sensor, burners, filter, venting, and a heat cycle. Boilers get pumps and pressure too."
        ]
      },
      {
        "h": "Spring (cooling)",
        "p": [
          "Outdoor coil, fan, and control components at the condenser, and a cool cycle if weather allows."
        ]
      },
      {
        "h": "What maintenance is not",
        "p": [
          "It is not a guarantee against every failure, and it is not a fake 'tune-up club' with invented discounts."
        ]
      }
    ],
    "faqs": [
      [
        "Heat pump â€” fall or spring?",
        "Both, because it runs year-round."
      ],
      [
        "Will you upsell a new furnace every visit?",
        "No. If the unit is fine we say so."
      ]
    ],
    "related": [
      "hvac-maintenance",
      "furnace-repair"
    ]
  }
];
const EXISTING_BLOG = [];

module.exports = { SITE, SERVICES, LOCATIONS, COMBO_SERVICE_SLUGS, NEIGHBOURHOODS, BLOG, EXISTING_BLOG };
